services:
  app:
    build: ./app
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
    networks:
      - sslip.io
    hostname: app-127-0-0-1.sslip.io
  auth:
    build: ./auth
    ports:
      - '3002:3002'
    environment:
      - PORT=3002
    networks:
      - sslip.io
    hostname: auth-127-0-0-1.sslip.io
  proxy:
    build: ./proxy
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - TLS_KEY=/certs/key.pem
      - TLS_CERT=/certs/cert.pem
    volumes:
      - ./certs:/certs:ro      
    depends_on:
      - app
    networks:
      - sslip.io
    hostname: proxy-127-0-0-1.sslip.io
networks:
  sslip.io:
    driver: bridge
