services:
  staples-tier-a-app:
    build: ./staples-tier-a-app
    ports:
      - "3001:3001"
    environment:
      - PORT=3001

  staples-auth-service:
    build: ./staples-auth-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002

  staples-rev-proxy:
    build: ./staples-rev-proxy
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - TARGET=http://staples-tier-a-app:3001
    depends_on:
      - staples-tier-a-app
      - staples-auth-service
