services:
  app:
    build: ./app
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
    networks:
      - lab.com
    hostname: app.lab.com
  auth:
    build: ./auth
    ports:
      - '3002:3002'
    environment:
      - PORT=3002
    networks:
      - lab.com
    hostname: auth.lab.com
  proxy:
    build: ./proxy
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - 'TARGET=http://app.lab.com:3001'
    depends_on:
      - app
    networks:
      - lab.com
    hostname: proxy.lab.com
networks:
  lab.com:
    driver: bridge
